// Lazy tab loading support for MainWindow.
// Generated by _generate_lazy_tabs.ps1

using System.Windows;
using System.Windows.Controls;
using System.Windows.Threading;

namespace AdHealthMonitor;

public partial class MainWindow
{
    // Tab UserControl backing fields
    private HealthTabPage? _HealthTab;
    private FindingsTabPage? _FindingsTab;
    private InfrastructureTabPage? _InfrastructureTab;
    private HistoryTabPage? _HistoryTab;
    private LogsTabPage? _LogsTab;
    private SecurityTabPage? _SecurityTab;
    private SettingsTabPage? _SettingsTab;
    private SchedulerTabPage? _SchedulerTab;

    // Ensure methods - create tab on first access
    private HealthTabPage EnsureHealthTab()
    {
        if (_HealthTab == null)
        {
            _HealthTab = new HealthTabPage();
            HealthTabHost.Content = _HealthTab;
            UpdateActionButtonStates();
            Dispatcher.BeginInvoke(() => RefreshDashboard(), DispatcherPriority.Background);
        }
        return _HealthTab;
    }
    private FindingsTabPage EnsureFindingsTab()
    {
        if (_FindingsTab == null)
        {
            _FindingsTab = new FindingsTabPage();
            FindingsTabHost.Content = _FindingsTab;
            UpdateActionButtonStates();
            Dispatcher.BeginInvoke(() => RefreshDashboard(), DispatcherPriority.Background);
        }
        return _FindingsTab;
    }
    private InfrastructureTabPage EnsureInfrastructureTab()
    {
        if (_InfrastructureTab == null)
        {
            _InfrastructureTab = new InfrastructureTabPage();
            InfrastructureTabHost.Content = _InfrastructureTab;
            Dispatcher.BeginInvoke(() => RefreshDashboard(), DispatcherPriority.Background);
        }
        return _InfrastructureTab;
    }
    private HistoryTabPage EnsureHistoryTab()
    {
        if (_HistoryTab == null)
        {
            _HistoryTab = new HistoryTabPage();
            HistoryTabHost.Content = _HistoryTab;
        }
        return _HistoryTab;
    }
    private LogsTabPage EnsureLogsTab()
    {
        if (_LogsTab == null)
        {
            _LogsTab = new LogsTabPage();
            if (LogsTabHost != null)
            {
                LogsTabHost.Content = _LogsTab;
            }
        }
        return _LogsTab;
    }
    private SecurityTabPage EnsureSecurityTab()
    {
        if (_SecurityTab == null)
        {
            _SecurityTab = new SecurityTabPage();
            SecurityTabHost.Content = _SecurityTab;
            Dispatcher.BeginInvoke(() => RefreshDashboard(), DispatcherPriority.Background);
        }
        return _SecurityTab;
    }
    private SettingsTabPage EnsureSettingsTab()
    {
        if (_SettingsTab == null)
        {
            _SettingsTab = new SettingsTabPage();
            SettingsTabHost.Content = _SettingsTab;
        }
        return _SettingsTab;
    }
    private SchedulerTabPage EnsureSchedulerTab()
    {
        if (_SchedulerTab == null)
        {
            _SchedulerTab = new SchedulerTabPage();
            SchedulerTabHost.Content = _SchedulerTab;
        }
        return _SchedulerTab;
    }

    // Lazy element access properties
    private TextBlock HealthSummaryText => EnsureHealthTab().HealthSummaryText;
    private TextBox ResultsTextBox => EnsureHealthTab().ResultsTextBox;
    private TextBlock DomainControllerCountText => EnsureHealthTab().DomainControllerCountText;
    private TextBlock PassingTestsText => EnsureHealthTab().PassingTestsText;
    private Border DetailsPanel => EnsureHealthTab().DetailsPanel;
    private Button ViewSelectedLogButton => EnsureHealthTab().ViewSelectedLogButton;
    private Button RunButton => EnsureHealthTab().RunButton;
    private TextBox SearchBox => EnsureHealthTab().SearchBox;
    private Button ExecutiveSummaryButton => EnsureHealthTab().ExecutiveSummaryButton;
    private DataGrid testResultsGrid => EnsureHealthTab().testResultsGrid;
    private TextBlock SearchPlaceholder => EnsureHealthTab().SearchPlaceholder;
    private Button StopButton => EnsureHealthTab().StopButton;
    private Button ExportButton => EnsureHealthTab().ExportButton;
    private Button SearchButton => EnsureHealthTab().SearchButton;
    private TextBlock CriticalFindingsText => EnsureHealthTab().CriticalFindingsText;
    private TextBlock HealthScoreText => EnsureHealthTab().HealthScoreText;
    private Button OpenFindingLogButton => EnsureFindingsTab().OpenFindingLogButton;
    private DataGrid dgFindings => EnsureFindingsTab().dgFindings;
    private TextBlock FindingsOpenCountText => EnsureFindingsTab().FindingsOpenCountText;
    private TextBlock FindingDetailsText => EnsureFindingsTab().FindingDetailsText;
    private TextBlock FindingsCriticalCountText => EnsureFindingsTab().FindingsCriticalCountText;
    private TextBlock FindingsHighCountText => EnsureFindingsTab().FindingsHighCountText;
    private TextBox FindingsSearchBox => EnsureFindingsTab().FindingsSearchBox;
    private TextBlock OuCountText => EnsureInfrastructureTab().OuCountText;
    private TextBlock GpoCountText => EnsureInfrastructureTab().GpoCountText;
    private TextBlock ComputerCountText => EnsureInfrastructureTab().ComputerCountText;
    private TextBlock InfrastructureDcCountText => EnsureInfrastructureTab().InfrastructureDcCountText;
    private TextBlock UserCountText => EnsureInfrastructureTab().UserCountText;
    private TextBlock DomainNameText => EnsureInfrastructureTab().DomainNameText;
    private TextBlock TrustCountText => EnsureInfrastructureTab().TrustCountText;
    private TextBlock DomainModeText => EnsureInfrastructureTab().DomainModeText;
    private TextBlock ForestNameText => EnsureInfrastructureTab().ForestNameText;
    private TextBlock InfrastructureSummaryText => EnsureInfrastructureTab().InfrastructureSummaryText;
    private Button CompareRunsButton => EnsureHistoryTab().CompareRunsButton;
    private DatePicker dpHistoryFilter => EnsureHistoryTab().dpHistoryFilter;
    private DataGrid dgTestHistory => EnsureHistoryTab().dgTestHistory;
    private TextBox txtHistorySearch => EnsureHistoryTab().txtHistorySearch;
    private Button ViewSelectedRunButton => EnsureHistoryTab().ViewSelectedRunButton;
    private ComboBox LogsResultFilter => EnsureLogsTab().LogsResultFilter;
    private ListBox LogsListBox => EnsureLogsTab().LogsListBox;
    private TextBlock LogsPassCountText => EnsureLogsTab().LogsPassCountText;
    private TextBox LogsSearchBox => EnsureLogsTab().LogsSearchBox;
    private TextBlock LogsSummaryText => EnsureLogsTab().LogsSummaryText;
    private TextBlock LogsVisibleCountText => EnsureLogsTab().LogsVisibleCountText;
    private TextBlock LogsFailureCountText => EnsureLogsTab().LogsFailureCountText;
    private Button PopOutLogViewerButton => EnsureLogsTab().PopOutLogViewerButton;
    private ComboBox LogsDcFilter => EnsureLogsTab().LogsDcFilter;
    private DataGrid dgLogsEntries => EnsureLogsTab().dgLogsEntries;
    private TextBlock LogsFileNameText => EnsureLogsTab().LogsFileNameText;
    private ComboBox LogsSectionFilter => EnsureLogsTab().LogsSectionFilter;
    private TextBlock LogsSearchPlaceholder => EnsureLogsTab().LogsSearchPlaceholder;
    private DataGrid dgSecurityFindings => EnsureSecurityTab().dgSecurityFindings;
    private TextBlock SecurityCriticalText => EnsureSecurityTab().SecurityCriticalText;
    private TextBlock SecuritySummaryText => EnsureSecurityTab().SecuritySummaryText;
    private TextBlock SecurityHighText => EnsureSecurityTab().SecurityHighText;
    private TextBlock SecurityPrivGroupCountText => EnsureSecurityTab().SecurityPrivGroupCountText;
    private TextBlock SecurityTotalFindingsText => EnsureSecurityTab().SecurityTotalFindingsText;
    private TextBlock PrivilegedInsightsText => EnsureSecurityTab().PrivilegedInsightsText;
    private Button SettingsTestEmailButton => EnsureSettingsTab().SettingsTestEmailButton;
    private CheckBox SettingsChkLdapBind => EnsureSettingsTab().SettingsChkLdapBind;
    private TextBox SettingsEmailTextBox => EnsureSettingsTab().SettingsEmailTextBox;
    private CheckBox SettingsChkTimeSkew => EnsureSettingsTab().SettingsChkTimeSkew;
    private CheckBox SettingsChkDns => EnsureSettingsTab().SettingsChkDns;
    private CheckBox SettingsChkReplication => EnsureSettingsTab().SettingsChkReplication;
    private TextBox SettingsDcTextBox => EnsureSettingsTab().SettingsDcTextBox;
    private CheckBox SettingsChkEmailScheduled => EnsureSettingsTab().SettingsChkEmailScheduled;
    private CheckBox SettingsChkCertDhcp => EnsureSettingsTab().SettingsChkCertDhcp;
    private CheckBox SettingsChkSmbSigning => EnsureSettingsTab().SettingsChkSmbSigning;
    private CheckBox SettingsChkEmailManual => EnsureSettingsTab().SettingsChkEmailManual;
    private DatePicker SchedulerStartDate => EnsureSchedulerTab().SchedulerStartDate;
    private TextBox SchedulerTaskName => EnsureSchedulerTab().SchedulerTaskName;
    private DataGrid SchedulerTaskList => EnsureSchedulerTab().SchedulerTaskList;
    private TextBox SchedulerDomainControllers => EnsureSchedulerTab().SchedulerDomainControllers;
    private ComboBox SchedulerFrequency => EnsureSchedulerTab().SchedulerFrequency;
    private TextBox SchedulerStartTime => EnsureSchedulerTab().SchedulerStartTime;

}
